### PR TITLE
added compatibility with models with module/namespace

### PR DESCRIPTION
**Pull request by abrkt**

### CODE REVIEW

**Comment by mensfeld** [comment]
+1 - really need this one

**Comment by dowglaz** [comment]
is there some forecast to merge this PR? ...

**Comment by twrk** [comment]
Hey all, since it seems like @cmer has abandoned this project (ie, not responding to PRs or tweets), I [forked](https://github.com/twrk/socialization) this repo and took inspiration from @abrkt's PR so that this gem will work with cases where a model inherits from another model; e.g., in my case:

    class Post < ActiveRecord::Base
      acts_as_likeable
    class ImagePost < Post
    class VideoPost < Post

You can set your Gemfile to point to the patched version like so, details [here](http://stackoverflow.com/questions/4070185/ruby-on-rails-patching-rack-and-deploying-it):

    gem 'socialization', :git => 'git://github.com/twrk/socialization.git'

**Comment by JeffTsui** [comment]
Thanks twrk, it works well!

**Comment by mensfeld** [comment]
@cmer :bowing_man:

**Comment by cmer** [comment]
Oy! Did that get closed automatically? I renamed `master` to `main` and I think it closed the PR.

**Comment by cmer** [comment]
I merged this manually in 2.0.1. Thanks guys!

**Pull request closed without merging**
